// Generated by CoffeeScript 1.4.0
var CoffeeScript, FileSys, Path, SMABSFileSys, handlePhaseOptions;

FileSys = require("fs");

Path = require("path");

CoffeeScript = require("coffee-script");

SMABSFileSys = require("../SMABSUtils");

handlePhaseOptions = function(phase, args) {
  if (!(phase.options != null)) {
    console.log("\tno options");
  }
};

exports.doPhase = function(phase, args) {
  if (!(phase.srcDir != null)) {
    console.log("You must specify a source dir for this phase");
    return;
  }
  handlePhaseOptions(phase);
  return SMABSFileSys.findAllOfType(args.rootDir + phase.srcDir, "coffee", true, function(name, parDir, fullPath) {
    var coffeeIn, compiledFile, jsOut;
    compiledFile = parDir + "/" + Path.basename(name, ".coffee") + ".js";
    console.log("\tcompiling " + name + " to " + compiledFile);
    SMABSFileSys.deleteFileIfExists(compiledFile);
    coffeeIn = FileSys.readFileSync(fullPath, "utf8");
    jsOut = CoffeeScript.compile(coffeeIn, {
      bare: true
    });
    return FileSys.writeFileSync(compiledFile, jsOut);
  });
};
