// Generated by CoffeeScript 1.4.0
var FileSys, MkDirP, SMABSFileSys, UglifyJS, handlePhaseOptions, verifyPhase;

FileSys = require("fs");

UglifyJS = require("uglify-js");

SMABSFileSys = require("../SMABSUtils");

MkDirP = require("mkdirp");

handlePhaseOptions = function(phase, args) {
  if (!(phase.options != null)) {
    console.log("\tno options");
  }
};

verifyPhase = function(phase, args) {
  if (!(phase.srcDir != null)) {
    console.log("\t*** No srcDir specified for phase, this is the directory to load the js from");
    return false;
  }
  if (!(phase.outDir != null)) {
    console.log("\t*** No outDir specified for phase, this is the directory to output the minified js to");
    return false;
  }
  return true;
};

exports.doPhase = function(phase, args) {
  if (!verifyPhase(phase, args)) {
    return false;
  }
  handlePhaseOptions(phase, args);
  MkDirP.sync(args.rootDir + phase.outDir);
  SMABSFileSys.findAllOfType(args.rootDir + phase.srcDir, "js", true, function(name, dir, path) {
    var outF, ug;
    console.log("\tMinifying " + name + " to ");
    outF = args.rootDir + "/" + phase.outDir + "/" + name;
    SMABSFileSys.deleteFileIfExists(outF);
    ug = UglifyJS.minify(path);
    return FileSys.writeFileSync(outF, ug.code);
  });
  return true;
};
