// Generated by CoffeeScript 1.4.0
var FileSys, FindIt, Path;

FileSys = require("fs");

FindIt = require("findit");

Path = require('path');

exports.deleteFileIfExists = function(path) {
  if (FileSys.existsSync(path)) {
    return FileSys.unlinkSync(path);
  }
};

exports.findAllOfType = function(rootDir, ext, filesOnly, cb) {
  var extT, file, files, nameExt, _i, _len, _results;
  extT = "." + ext;
  files = FindIt.sync(rootDir);
  _results = [];
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    nameExt = Path.basename(file);
    if (Path.extname(nameExt) === extT) {
      _results.push(cb(nameExt, Path.dirname(file), file));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

exports.copyFile = function(from, to, overwrite) {
  var data;
  if (!overwrite && FileSys.existsSync(to)) {
    return;
  }
  exports.deleteFileIfExists(to);
  data = FileSys.readFileSync(from);
  return FileSys.writeFileSync(to, data);
};
